[project]
name = "insurance-analytics-project-dbt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "databricks>=0.2",
    "dbt>=1.0.0.40.14",
    "dbt-core>=1.11.2",
    "dbt-databricks>=1.10.9",
]
